# Generated by Django 6.0.3 on 2026-04-30 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("detection", "0003_detection_care_tips_detection_prevention_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="detection",
            name="scientific_name",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
